fullname: Trajectories
shortname: trajectories
organization: math-comp
opam_name: coq-mathcomp-trajectories
community: false
action: true
nix: false
coqdoc: false

synopsis: >-
  Trajectories
description: |-
  TODO
authors:
- name: Reynald Affeldt
  initial: true
- name: Yves Bertot
  initial: true

opam-file-maintainer: Reynald Affeldt <reynald.affeldt@aist.go.jp>

opam-file-version: dev

license:
  fullname: CeCILL-C
  identifier: CECILL-C
  file: LICENSE

supported_coq_versions:
  text: Coq >= 8.15, MathComp >= 1.15
  opam: '{ (>= "8.14" & < "8.17~") | (= "dev") }'

tested_coq_opam_versions:
- version: '1.15.0-coq-8.15'
  repo: 'mathcomp/mathcomp'
- version: '1.15.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '1.16.0-coq-8.15'
  repo: 'mathcomp/mathcomp'
- version: '1.16.0-coq-8.16'
  repo: 'mathcomp/mathcomp'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{ (>= "1.15.0" & < "1.17~") | (= "dev") }'
  description: |-
    [MathComp ssreflect 1.15 or later](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-fingroup
    version: '{ (>= "1.15.0" & < "1.17~") | (= "dev") }'
  description: |-
    [MathComp fingroup 1.15 or later](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-algebra
    version: '{ (>= "1.15.0" & < "1.17~") | (= "dev") }'
  description: |-
    [MathComp algebra 1.15 or later](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-solvable
    version: '{ (>= "1.15.0" & < "1.17~") | (= "dev") }'
  description: |-
    [MathComp solvable 1.15 or later](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-field
    version: '{ (>= "1.15.0" & < "1.17~") | (= "dev") }'
  description: |-
    [MathComp field 1.15 or later](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-real-closed
    version: '{ (>= "1.1.3") | (= "dev") }'
  description: |-
    [Mathcomp real closed 1.1.3 or later](https://github.com/math-comp/real-closed/)
- opam:
    name: coq-mathcomp-algebra-tactics
    version: '{ (>= "1.0.0") | (= "dev") }'
  description: |-
    [Algebra tactics 1.0.0](https://github.com/math-comp/algebra-tactics)
- opam:
    name: coq-mathcomp-analysis
    version: '{ (>= "0.5.4") & (< "0.7~")}'
  description: |-
    [MathComp analysis](https://github.com/math-comp/analysis)
- opam:
    name: coq-infotheo
    version: '{ >= "0.5.1" & < "0.6~"}'
  description: |-
    [Infotheo](https://github.com/affeldt-aist/infotheo)

namespace: mathcomp.trajectories

keywords:
- name: trajectories

categories:
- name: Mathematics/Real Calculus and Topology

publications:
- pub_url: TODO
  pub_title:  TODO
  pub_doi: TODO

documentation: |-
  ## Disclaimer
 
  TODO

  ## Documentation

  tentative update of https://gitlab.inria.fr/bertot/cadcoq

  references:
  - Root Isolation for one-variable polynomials (2010)
    https://wiki.portal.chalmers.se/cse/uploads/ForMath/rootisol
  - A formal study of Bernstein coefficients and polynomials (2010)
    https://hal.inria.fr/inria-00503017v2/document
  - Theorem of three circles in Coq (2013)
    https://arxiv.org/abs/1306.0783

  ## Development information

  TODO

  ## Previous work reused at the time of the first releases

  TODO

  ## Acknowledgments

  TODO
